// 可選的歌手。clues 對應 js/clues/ 裡手寫的題庫；沒有題庫的歌手，線索模式改用 iTunes 資料自動出題。
// 沒寫到的欄位（tagline、ranks、colors、icon、countries）會用所屬地區的預設值。
// related：同團的團員或所屬團體，猜歌手模式不會讓他們同時出現在選項裡。

window.REGIONS = [
  { id: "tw", name: "台灣", icon: "🎤", countries: ["tw", "us"], colors: { accent: "#86d5cd", accent2: "#b9dfbf", onAccent: "#142927" } },
  { id: "twh", name: "台語", icon: "🏮", countries: ["tw", "us"], colors: { accent: "#d5ad86", accent2: "#dfd4b9", onAccent: "#291e14" } },
  { id: "cn", name: "中國", icon: "🐉", countries: ["tw", "cn", "us"], colors: { accent: "#d58b86", accent2: "#dfd0b9", onAccent: "#291514" } },
  { id: "jp", name: "日本", icon: "🌸", countries: ["tw", "jp", "us"], colors: { accent: "#d58697", accent2: "#dfb9c0", onAccent: "#291419" } },
  { id: "kr", name: "韓國", icon: "💜", countries: ["tw", "kr", "us"], colors: { accent: "#9086d5", accent2: "#b9d8df", onAccent: "#171429" } },
  { id: "west", name: "歐美", icon: "🎸", countries: ["tw", "us"], colors: { accent: "#8690d5", accent2: "#cfb9df", onAccent: "#141729" } },
  { id: "latin", name: "拉丁", icon: "🌶️", countries: ["tw", "us", "mx"], colors: { accent: "#d5bc86", accent2: "#dfb9b9", onAccent: "#292314" } },
  { id: "in", name: "印度", icon: "🪷", countries: ["in", "us"], colors: { accent: "#d5ad86", accent2: "#b9dfdc", onAccent: "#291f14" } },
  { id: "th", name: "泰國", icon: "🐘", countries: ["th", "us"], colors: { accent: "#d5c286", accent2: "#b9cddf", onAccent: "#292414" } },
];

window.ARTISTS = [
  // ---------- 台灣 ----------
  { region: "tw", id: "jay", name: "周杰倫", terms: ["周杰倫", "Jay Chou"], match: /周杰倫|周杰伦|jay chou/i },
  { region: "tw", id: "mayday", name: "五月天", terms: ["五月天", "Mayday"], match: /五月天|^mayday\b(?! parade)/i },
  { region: "tw", id: "jolin", name: "蔡依林", terms: ["蔡依林", "Jolin Tsai"], match: /蔡依林|jolin tsai/i },
  { region: "tw", id: "amei", name: "張惠妹", terms: ["張惠妹", "A-Mei"], match: /張惠妹|张惠妹|a-?mei|阿密特/i },
  { region: "tw", id: "hebe", name: "田馥甄", terms: ["田馥甄", "Hebe Tien"], match: /田馥甄|hebe tien/i, related: ["she"] },
  { region: "tw", id: "yoga", name: "林宥嘉", terms: ["林宥嘉", "Yoga Lin"], match: /林宥嘉|yoga lin/i },
  { region: "tw", id: "accusefive", name: "告五人", terms: ["告五人", "Accusefive"], match: /告五人|accusefive/i },
  { region: "tw", id: "crowdlu", name: "盧廣仲", terms: ["盧廣仲", "Crowd Lu"], match: /盧廣仲|卢广仲|crowd lu/i },
  { region: "tw", id: "lala", name: "徐佳瑩", terms: ["徐佳瑩", "LaLa Hsu"], match: /徐佳瑩|徐佳莹|lala hsu/i },
  { region: "tw", id: "rainie", name: "楊丞琳", terms: ["楊丞琳", "Rainie Yang"], match: /楊丞琳|杨丞琳|rainie yang/i },
  {
    region: "tw",
    id: "hsiao",
    name: "蕭煌奇",
    terms: ["蕭煌奇"],
    match: /蕭煌奇|萧煌奇|ricky hsiao/i,
    colors: { accent: "#86d5d1", accent2: "#b9dfc4", onAccent: "#142928" },
  },

  // ---------- 台語 ----------
  { region: "twh", id: "jody", name: "江蕙", terms: ["江蕙", "Jody Chiang"], match: /江蕙|jody chiang/i },
  { region: "twh", id: "wubai", name: "伍佰", terms: ["伍佰", "Wu Bai"], match: /伍佰|wu bai/i },
  { region: "twh", id: "eggplantegg", name: "茄子蛋", terms: ["茄子蛋", "EggPlantEgg"], match: /茄子蛋|eggplantegg/i },
  { region: "twh", id: "jeannie", name: "謝金燕", terms: ["謝金燕", "Jeannie Hsieh"], match: /謝金燕|谢金燕|jeannie hsieh/i },
  { region: "twh", id: "chenlei", name: "陳雷", terms: ["陳雷"], match: /陳雷|陈雷/ },

  // ---------- 日本 ----------
  {
    region: "jp",
    id: "yoasobi",
    name: "YOASOBI",
    icon: "🌙",
    tagline: "把小說變成音樂的兩人組，你認得幾首？",
    terms: ["yoasobi"],
    match: /yoasobi/i,
    // E-SIDE 系列是英文版，歌名不同但旋律一樣，排除以免選項重複
    excludeCollection: /e-side/i,
    colors: { accent: "#869bd5", accent2: "#dfb9cf", onAccent: "#141a29" },
    ranks: ["Ayase 和 ikura 本人？🌙", "資深 YOASOBI 迷 📖", "剛讀完第一本 THE BOOK 📘", "先去把《THE BOOK》聽完再來 📀"],
  },
  { region: "jp", id: "yonezu", name: "米津玄師", terms: ["米津玄師", "Kenshi Yonezu"], match: /米津玄師|米津玄师|kenshi yonezu/i },
  { region: "jp", id: "mga", name: "Mrs. GREEN APPLE", short: "Mrs. GREEN APPLE", terms: ["Mrs. GREEN APPLE"], match: /mrs\.? ?green apple/i },
  { region: "jp", id: "higedan", name: "Official髭男dism", short: "髭男", terms: ["Official髭男dism", "Official HIGE DANdism"], match: /official髭男dism|official hige dandism/i },
  { region: "jp", id: "kinggnu", name: "King Gnu", terms: ["King Gnu"], match: /king gnu/i },
  { region: "jp", id: "ado", name: "Ado", terms: ["Ado"], match: /^ado(\s*[,&×x、]|$)/i },
  { region: "jp", id: "aimyon", name: "あいみょん", terms: ["あいみょん", "Aimyon"], match: /あいみょん|aimyon/i },
  { region: "jp", id: "backnumber", name: "back number", terms: ["back number"], match: /back number/i },
  { region: "jp", id: "utada", name: "宇多田ヒカル", short: "宇多田", terms: ["宇多田ヒカル", "Hikaru Utada"], match: /宇多田ヒカル|hikaru utada|^utada$/i },
  { region: "jp", id: "vaundy", name: "Vaundy", terms: ["Vaundy"], match: /vaundy/i },
  // 區分大小寫，避免和泰國的 LISA 混在一起
  { region: "jp", id: "lisa-jp", name: "LiSA", terms: ["LiSA"], match: /^LiSA(\s*[,&×x、]|$)/ },

  // ---------- 歐美 ----------
  {
    region: "west",
    id: "gaga",
    name: "Lady Gaga",
    short: "Gaga",
    icon: "⚡",
    tagline: "你是真正的 Little Monster 嗎？",
    terms: ["lady gaga"],
    match: /lady gaga/i,
    // 《捍衛戰士：獨行俠》原聲帶大多是她和 Hans Zimmer 等人掛名的配樂，太難猜
    excludeCollection: /top gun/i,
    // 《Chromatica》的三段管弦樂間奏很好玩，雖然很短也保留
    allowShort: /^chromatica i+$/i,
    colors: { accent: "#d586ad", accent2: "#ccb9df", onAccent: "#29141e" },
    ranks: ["Mother Monster 本人？👑", "資深 Little Monster 🐾", "還在練舞的 Monster 💃", "先去把《The Fame》聽完再來 📀"],
  },
  {
    region: "west",
    id: "mj",
    name: "Michael Jackson",
    short: "MJ",
    icon: "🧤",
    tagline: "你跟得上 King of Pop 的舞步嗎？",
    terms: ["michael jackson"],
    match: /michael jackson/i,
    colors: { accent: "#d5bd86", accent2: "#dfd5b9", onAccent: "#292314" },
    ranks: ["King of Pop 本人？👑", "月球漫步大師 🕺", "還在練 moonwalk 的新手 🧦", "先去把《Thriller》聽完再來 📀"],
  },
  {
    region: "west",
    id: "bruno",
    name: "Bruno Mars",
    short: "Bruno",
    icon: "🎩",
    tagline: "你是真正的 Hooligan 嗎？",
    terms: ["bruno mars"],
    match: /bruno mars/i,
    colors: { accent: "#d59f86", accent2: "#dfd3b9", onAccent: "#291b14" },
    ranks: ["Bruno 本人？🎩", "資深 Hooligan 🕶️", "剛戴上 24K 金鍊的新手 🪙", "先去把《Doo-Wops & Hooligans》聽完再來 📀"],
  },
  {
    region: "west",
    id: "ariana",
    name: "Ariana Grande",
    short: "Ariana",
    icon: "🎀",
    tagline: "你是真正的 Arianator 嗎？",
    terms: ["ariana grande"],
    match: /ariana grande/i,
    colors: { accent: "#a786d5", accent2: "#dfb9cc", onAccent: "#1d1429" },
    ranks: ["Ariana 本人？🎀", "資深 Arianator 💜", "正在綁高馬尾的新手 🎀", "先去把《thank u, next》聽完再來 📀"],
  },
  { region: "west", id: "taylor", name: "Taylor Swift", short: "Taylor", tagline: "你是真正的 Swiftie 嗎？", terms: ["Taylor Swift"], match: /taylor swift/i },
  { region: "west", id: "edsheeran", name: "Ed Sheeran", short: "Ed Sheeran", terms: ["Ed Sheeran"], match: /ed sheeran/i },
  { region: "west", id: "billie", name: "Billie Eilish", short: "Billie", terms: ["Billie Eilish"], match: /billie eilish/i },
  { region: "west", id: "weeknd", name: "The Weeknd", terms: ["The Weeknd"], match: /the weeknd/i },
  { region: "west", id: "adele", name: "Adele", terms: ["Adele"], match: /^adele(\s*[,&]|$)/i },
  { region: "west", id: "dualipa", name: "Dua Lipa", terms: ["Dua Lipa"], match: /dua lipa/i },
  { region: "west", id: "coldplay", name: "Coldplay", terms: ["Coldplay"], match: /coldplay/i },
  { region: "west", id: "beyonce", name: "Beyoncé", terms: ["Beyonce"], match: /beyonc[eé]/i },
  { region: "west", id: "bieber", name: "Justin Bieber", short: "Bieber", terms: ["Justin Bieber"], match: /justin bieber/i },
  { region: "west", id: "olivia", name: "Olivia Rodrigo", short: "Olivia", terms: ["Olivia Rodrigo"], match: /olivia rodrigo/i },

  // ---------- 中國 ----------
  { region: "cn", id: "faye", name: "王菲", terms: ["王菲", "Faye Wong"], match: /王菲|faye wong/i },
  { region: "cn", id: "naying", name: "那英", terms: ["那英", "Na Ying"], match: /那英|na ying/i },
  { region: "cn", id: "zhoushen", name: "周深", terms: ["周深", "Zhou Shen"], match: /周深|zhou shen|charlie zhou/i },
  { region: "cn", id: "maobuyi", name: "毛不易", terms: ["毛不易", "Mao Buyi"], match: /毛不易|mao buyi/i },
  { region: "cn", id: "ronghao", name: "李榮浩", terms: ["李榮浩", "李荣浩", "Ronghao Li"], match: /李榮浩|李荣浩|ronghao li|li ronghao/i },
  { region: "cn", id: "huachenyu", name: "華晨宇", terms: ["華晨宇", "华晨宇", "Hua Chenyu"], match: /華晨宇|华晨宇|hua chenyu/i },
  { region: "cn", id: "janezhang", name: "張靚穎", terms: ["張靚穎", "张靓颖", "Jane Zhang"], match: /張靚穎|张靓颖|jane zhang/i },
  { region: "cn", id: "joker", name: "薛之謙", terms: ["薛之謙", "薛之谦", "Joker Xue"], match: /薛之謙|薛之谦|joker xue/i },
  { region: "cn", id: "lijian", name: "李健", terms: ["李健", "Li Jian"], match: /^李健($|\s*[,&])|li jian/i },
  { region: "cn", id: "pushu", name: "朴樹", terms: ["朴樹", "朴树", "Pu Shu"], match: /朴樹|朴树|樸樹|pu shu/i },

  // ---------- 印度 ----------
  { region: "in", id: "arijit", name: "Arijit Singh", short: "Arijit", terms: ["Arijit Singh"], match: /arijit singh/i },
  { region: "in", id: "rahman", name: "A.R. Rahman", terms: ["A.R. Rahman"], match: /a\.?\s?r\.?\s?rahman/i },
  { region: "in", id: "shreya", name: "Shreya Ghoshal", short: "Shreya", terms: ["Shreya Ghoshal"], match: /shreya ghoshal/i },

  // ---------- 泰國 ----------
  { region: "th", id: "bodyslam", name: "Bodyslam", terms: ["Bodyslam", "บอดี้สแลม"], match: /bodyslam|บอดี้สแลม/i },
  { region: "th", id: "palmy", name: "Palmy", terms: ["Palmy", "ปาล์มมี่"], match: /palmy|ปาล์มมี่/i },
  { region: "th", id: "phum", name: "Phum Viphurit", short: "Phum", terms: ["Phum Viphurit"], match: /phum viphurit/i },
];


// ---------- 全球百大裡原本沒有的歌手 ----------
// 名字很短或很常見的，用 ^…$ 比對整個歌手名稱，避免抓到同名的其他人
const more = (region, id, name, terms, match, extra = {}) => ({ region, id, name, terms, match, ...extra });
window.ARTISTS.push(
  more("west", "drake", "Drake", ["Drake"], /^drake(\s*[,&]|$)/i),
  more("west", "eminem", "Eminem", ["Eminem"], /eminem/i),
  more("west", "rihanna", "Rihanna", ["Rihanna"], /rihanna/i),
  more("west", "postmalone", "Post Malone", ["Post Malone"], /post malone/i),
  more("west", "kendrick", "Kendrick Lamar", ["Kendrick Lamar"], /kendrick lamar/i, { short: "Kendrick" }),
  more("west", "sza", "SZA", ["SZA"], /^sza(\s*[,&]|$)/i),
  more("west", "dojacat", "Doja Cat", ["Doja Cat"], /doja cat/i),
  more("west", "harrystyles", "Harry Styles", ["Harry Styles"], /harry styles/i, { short: "Harry" }),
  more("west", "imaginedragons", "Imagine Dragons", ["Imagine Dragons"], /imagine dragons/i),
  more("west", "maroon5", "Maroon 5", ["Maroon 5"], /maroon 5/i),
  more("west", "katyperry", "Katy Perry", ["Katy Perry"], /katy perry/i, { short: "Katy" }),
  more("west", "sabrina", "Sabrina Carpenter", ["Sabrina Carpenter"], /sabrina carpenter/i, { short: "Sabrina" }),
  more("west", "lanadelrey", "Lana Del Rey", ["Lana Del Rey"], /lana del rey/i, { short: "Lana" }),
  more("west", "arcticmonkeys", "Arctic Monkeys", ["Arctic Monkeys"], /arctic monkeys/i),
  more("west", "linkinpark", "Linkin Park", ["Linkin Park"], /linkin park/i),
  more("west", "queen", "Queen", ["Queen"], /^queen(\s*[,&]|$)/i),
  more("west", "beatles", "The Beatles", ["The Beatles"], /^the beatles$/i),
  more("west", "eltonjohn", "Elton John", ["Elton John"], /elton john/i),
  more("west", "madonna", "Madonna", ["Madonna"], /^madonna(\s*[,&]|$)/i),
  more("west", "whitney", "Whitney Houston", ["Whitney Houston"], /whitney houston/i, { short: "Whitney" }),
  more("west", "mariah", "Mariah Carey", ["Mariah Carey"], /mariah carey/i, { short: "Mariah" }),
  more("west", "elvis", "Elvis Presley", ["Elvis Presley"], /elvis presley/i, { short: "Elvis" }),
  more("west", "abba", "ABBA", ["ABBA"], /^abba$/i),
  more("west", "bobmarley", "Bob Marley", ["Bob Marley"], /bob marley/i),
  more("west", "nirvana", "Nirvana", ["Nirvana"], /^nirvana$/i),
  more("west", "metallica", "Metallica", ["Metallica"], /^metallica(\s*[,&]|$)/i),
  more("west", "acdc", "AC/DC", ["AC/DC"], /^ac\/dc$/i),
  more("west", "gnr", "Guns N' Roses", ["Guns N' Roses"], /guns n['’]? roses/i),
  more("west", "rhcp", "Red Hot Chili Peppers", ["Red Hot Chili Peppers"], /red hot chili peppers/i, { short: "嗆辣紅椒" }),
  more("west", "oasis", "Oasis", ["Oasis"], /^oasis$/i),
  more("west", "radiohead", "Radiohead", ["Radiohead"], /^radiohead$/i),
  more("west", "u2", "U2", ["U2"], /^u2(\s*[,&]|$)/i),
  more("west", "bonjovi", "Bon Jovi", ["Bon Jovi"], /^bon jovi$/i),
  more("west", "pinkfloyd", "Pink Floyd", ["Pink Floyd"], /^pink floyd$/i),
  more("west", "ledzeppelin", "Led Zeppelin", ["Led Zeppelin"], /^led zeppelin$/i),
  more("west", "rollingstones", "The Rolling Stones", ["The Rolling Stones"], /rolling stones/i, { short: "滾石" }),
  more("west", "fleetwoodmac", "Fleetwood Mac", ["Fleetwood Mac"], /^fleetwood mac$/i),
  more("west", "eagles", "Eagles", ["Eagles"], /^eagles$/i),
  more("west", "prince", "Prince", ["Prince"], /^prince(\s*[,&]|$)/i),
  more("west", "steviewonder", "Stevie Wonder", ["Stevie Wonder"], /stevie wonder/i, { short: "Stevie" }),
  more("west", "bowie", "David Bowie", ["David Bowie"], /david bowie/i, { short: "Bowie" }),
  more("west", "britney", "Britney Spears", ["Britney Spears"], /britney spears/i, { short: "Britney" }),
  more("west", "timberlake", "Justin Timberlake", ["Justin Timberlake"], /justin timberlake/i, { short: "JT" }),
  more("west", "usher", "Usher", ["Usher"], /^usher(\s*[,&]|$)/i),
  more("west", "aliciakeys", "Alicia Keys", ["Alicia Keys"], /alicia keys/i, { short: "Alicia" }),
  more("west", "sia", "Sia", ["Sia"], /^sia(\s*[,&]|$)/i),
  more("west", "shawnmendes", "Shawn Mendes", ["Shawn Mendes"], /shawn mendes/i, { short: "Shawn" }),
  more("west", "charlieputh", "Charlie Puth", ["Charlie Puth"], /charlie puth/i, { short: "Charlie" }),
  more("west", "samsmith", "Sam Smith", ["Sam Smith"], /^sam smith(\s*[,&]|$)/i),
  more("west", "capaldi", "Lewis Capaldi", ["Lewis Capaldi"], /lewis capaldi/i, { short: "Capaldi" }),
  more("west", "onerepublic", "OneRepublic", ["OneRepublic"], /onerepublic/i),
  more("west", "calvinharris", "Calvin Harris", ["Calvin Harris"], /calvin harris/i),
  more("west", "guetta", "David Guetta", ["David Guetta"], /david guetta/i, { short: "Guetta" }),
  more("west", "avicii", "Avicii", ["Avicii"], /avicii/i),
  more("west", "daftpunk", "Daft Punk", ["Daft Punk"], /daft punk/i),
  more("west", "marshmello", "Marshmello", ["Marshmello"], /marshmello/i),
  more("west", "chainsmokers", "The Chainsmokers", ["The Chainsmokers"], /chainsmokers/i),
  more("west", "travisscott", "Travis Scott", ["Travis Scott"], /travis scott/i),
  more("west", "future", "Future", ["Future"], /^future(\s*[,&]|$)/i),
  more("west", "nickiminaj", "Nicki Minaj", ["Nicki Minaj"], /nicki minaj/i, { short: "Nicki" }),
  more("west", "cardib", "Cardi B", ["Cardi B"], /^cardi b(\s*[,&]|$)/i),
  more("west", "jayz", "JAY-Z", ["JAY-Z"], /^jay[- ]?z(\s*[,&]|$)/i),
  more("west", "snoop", "Snoop Dogg", ["Snoop Dogg"], /snoop dogg/i, { short: "Snoop" }),
  more("west", "fiftycent", "50 Cent", ["50 Cent"], /^50 cent(\s*[,&]|$)/i),
  more("west", "selena", "Selena Gomez", ["Selena Gomez"], /selena gomez/i, { short: "Selena" }),
  more("west", "miley", "Miley Cyrus", ["Miley Cyrus"], /miley cyrus/i, { short: "Miley" }),
  more("west", "pink", "P!nk", ["P!nk", "Pink"], /^p!nk(\s*[,&]|$)/i),
  more("west", "greenday", "Green Day", ["Green Day"], /^green day$/i),
  more("west", "twentyonepilots", "Twenty One Pilots", ["Twenty One Pilots"], /twenty one pilots/i, { short: "21 Pilots" }),
  more("west", "frankocean", "Frank Ocean", ["Frank Ocean"], /frank ocean/i),
  more("west", "celine", "Céline Dion", ["Celine Dion"], /c[eé]line dion/i, { short: "Céline" }),
  more("west", "morganwallen", "Morgan Wallen", ["Morgan Wallen"], /morgan wallen/i),

  more("kr", "bts", "BTS", ["BTS"], /^bts(\s*[,&]|$)/i, { tagline: "你是真正的 ARMY 嗎？" }),
  more("kr", "blackpink", "BLACKPINK", ["BLACKPINK"], /^blackpink(\s*[,&]|$)/i, { tagline: "你是真正的 BLINK 嗎？" }),
  more("kr", "twice", "TWICE", ["TWICE"], /^twice(\s*[,&]|$)/i),
  more("kr", "newjeans", "NewJeans", ["NewJeans"], /^newjeans(\s*[,&]|$)/i),
  more("kr", "straykids", "Stray Kids", ["Stray Kids"], /^stray kids(\s*[,&]|$)/i),
  more("kr", "psy", "PSY", ["PSY"], /^psy(\s*[,&]|$)/i),
  more("kr", "iu", "IU", ["IU"], /^iu(\s*[,&(]|$)/i),

  more("latin", "badbunny", "Bad Bunny", ["Bad Bunny"], /bad bunny/i),
  more("latin", "shakira", "Shakira", ["Shakira"], /shakira/i),
  more("latin", "jbalvin", "J Balvin", ["J Balvin"], /j\.? ?balvin/i),
  more("latin", "karolg", "KAROL G", ["KAROL G"], /karol g\b/i),
  more("latin", "daddyyankee", "Daddy Yankee", ["Daddy Yankee"], /daddy yankee/i),
  more("latin", "ozuna", "Ozuna", ["Ozuna"], /^ozuna(\s*[,&]|$)/i),
  more("latin", "rosalia", "ROSALÍA", ["Rosalia"], /^rosal[ií]a(\s*[,&]|$)/i),
);

// ---------- 台灣、台語加碼 ----------
// 中文名字都很獨特，比對簡繁體與英文名即可；很短的名字用 ^…$ 避免抓到別人
window.ARTISTS.push(
  more("tw", "cyndi", "王心凌", ["王心凌", "Cyndi Wang"], /王心凌|cyndi wang/i),
  more("tw", "sodagreen", "蘇打綠", ["蘇打綠", "Sodagreen"], /蘇打綠|苏打绿|sodagreen|魚丁糸/i),
  more("tw", "qingfeng", "吳青峰", ["吳青峰", "Qing Feng Wu"], /吳青峰|吴青峰|qing ?feng wu|wu tsing-fong/i),
  more("tw", "weibird", "韋禮安", ["韋禮安", "WeiBird"], /韋禮安|韦礼安|weibird/i),
  more("tw", "cheerchen", "陳綺貞", ["陳綺貞", "Cheer Chen"], /陳綺貞|陈绮贞|cheer chen/i),
  more("tw", "jonathanlee", "李宗盛", ["李宗盛", "Jonathan Lee"], /李宗盛|jonathan lee/i),
  more("tw", "tomchang", "張雨生", ["張雨生"], /張雨生|张雨生/),
  more("tw", "teresateng", "鄧麗君", ["鄧麗君", "Teresa Teng"], /鄧麗君|邓丽君|teresa teng/i),
  more("tw", "feiyuching", "費玉清", ["費玉清", "Fei Yu-Ching"], /費玉清|费玉清|fei yu-?ching/i),
  more("tw", "reneliu", "劉若英", ["劉若英", "Rene Liu"], /劉若英|刘若英|rene liu/i),
  more("tw", "davidtao", "陶喆", ["陶喆", "David Tao"], /陶喆|david tao/i),
  more("tw", "angelachang", "張韶涵", ["張韶涵", "Angela Chang"], /張韶涵|张韶涵|angela chang/i),
  more("tw", "she", "S.H.E", ["S.H.E"], /^s\.?h\.?e(\s*[,&]|$)/i),
  more("tw", "powerstation", "動力火車", ["動力火車", "Power Station"], /動力火車|动力火车|power station/i),
  more("tw", "831", "八三夭", ["八三夭", "831"], /八三夭|^831$/i),
  more("tw", "caodong", "草東沒有派對", ["草東沒有派對", "No Party For Cao Dong"], /草東沒有派對|草东没有派对|no party for cao dong/i, { short: "草東" }),
  more("tw", "sunsetrollercoaster", "落日飛車", ["落日飛車", "Sunset Rollercoaster"], /落日飛車|落日飞车|sunset rollercoaster/i),
  more("tw", "mangojump", "芒果醬", ["芒果醬", "Mango Jump"], /芒果醬|芒果酱|mango jump/i),
  // 管弦樂團，演奏台灣作曲家的作品與台灣歌曲改編，沒有人聲，歌詞模式玩不了
  more("tw", "onesong", "灣聲樂團", ["灣聲樂團", "One Song Orchestra"], /灣聲|湾声|one song orchestra/i, { short: "灣聲" }),
  more("tw", "waawei", "魏如萱", ["魏如萱", "Waa Wei"], /魏如萱|waa wei/i),
  more("tw", "9m88", "9m88", ["9m88"], /^9m88(\s*[,&]|$)/i),
  more("tw", "deserts", "張懸／安溥", ["張懸", "安溥", "Deserts Chang"], /張懸|张悬|安溥|deserts chang/i, { short: "張懸" }),
  more("tw", "ericchou", "周興哲", ["周興哲", "Eric Chou"], /周興哲|周兴哲|eric chou/i),
  more("tw", "jamhsiao", "蕭敬騰", ["蕭敬騰", "Jam Hsiao"], /蕭敬騰|萧敬腾|jam hsiao/i),
  more("tw", "harlemyu", "庾澄慶", ["庾澄慶", "Harlem Yu"], /庾澄慶|庾澄庆|harlem yu/i),
  more("tw", "wakin", "周華健", ["周華健", "Wakin Chau"], /周華健|周华健|wakin chau|emil chau/i),
  more("tw", "richiejen", "任賢齊", ["任賢齊", "Richie Jen"], /任賢齊|任贤齐|richie (jen|ren)/i),
  more("tw", "ayue", "張震嶽", ["張震嶽", "A-Yue"], /張震嶽|张震岳|a-?yue|ayal komod/i),
  more("tw", "mj116", "頑童MJ116", ["頑童MJ116", "MJ116"], /頑童|顽童|mj116/i),
  more("tw", "cosmospeople", "宇宙人", ["宇宙人", "Cosmos People"], /宇宙人|cosmos people/i),
  more("tw", "eveai", "艾怡良", ["艾怡良", "Eve Ai"], /艾怡良|eve ai/i),
  more("tw", "naiwen", "楊乃文", ["楊乃文", "Faith Yang"], /楊乃文|杨乃文|faith yang/i),
  more("tw", "chyichin", "齊秦", ["齊秦", "Chyi Chin"], /齊秦|齐秦|chyi chin/i),
  more("tw", "maggiechiang", "江美琪", ["江美琪", "Maggie Chiang"], /江美琪|maggie chiang/i),
  more("tw", "wilberpan", "潘瑋柏", ["潘瑋柏", "Wilber Pan"], /潘瑋柏|潘玮柏|wilber pan/i),

  more("twh", "yehchitien", "葉啟田", ["葉啟田"], /葉啟田|叶启田/),
  more("twh", "hungjunghung", "洪榮宏", ["洪榮宏"], /洪榮宏|洪荣宏/),
  more("twh", "huangyiling", "黃乙玲", ["黃乙玲"], /黃乙玲|黄乙玲/),
  more("twh", "lungchienyu", "龍千玉", ["龍千玉"], /龍千玉|龙千玉/),
  more("twh", "tsaichiufeng", "蔡秋鳳", ["蔡秋鳳"], /蔡秋鳳|蔡秋凤/),
  more("twh", "chanyawen", "詹雅雯", ["詹雅雯"], /詹雅雯/),
  more("twh", "huangfei", "黃妃", ["黃妃"], /^(黃妃|黄妃)($|\s*[,&])/),
  more("twh", "tsenghsinmei", "曾心梅", ["曾心梅"], /曾心梅/),
  more("twh", "chenyalan", "陳亞蘭", ["陳亞蘭"], /陳亞蘭|陈亚兰/),
  more("twh", "wangshihhsien", "王識賢", ["王識賢"], /王識賢|王识贤/),
  more("twh", "wengliyu", "翁立友", ["翁立友"], /翁立友/),
  more("twh", "chiangchihfeng", "江志豐", ["江志豐"], /江志豐|江志丰/),
  more("twh", "huangshanliang", "荒山亮", ["荒山亮"], /荒山亮/),
  more("twh", "chenyingchieh", "陳盈潔", ["陳盈潔"], /陳盈潔|陈盈洁/),
  more("twh", "chengchinyi", "鄭進一", ["鄭進一"], /鄭進一|郑进一/),
  more("twh", "loshihfeng", "羅時豐", ["羅時豐"], /羅時豐|罗时丰/),
  more("twh", "tsaihsiaohu", "蔡小虎", ["蔡小虎"], /蔡小虎/),
  more("twh", "wushenmei", "吳申梅", ["吳申梅"], /吳申梅|吴申梅/),
  more("twh", "changhsiuching", "張秀卿", ["張秀卿"], /張秀卿|张秀卿/),
  more("twh", "hungyifeng", "洪一峰", ["洪一峰"], /洪一峰/),
  more("twh", "wenhsia", "文夏", ["文夏"], /^文夏($|\s*[,&])/),
  more("twh", "chenmingchang", "陳明章", ["陳明章"], /陳明章|陈明章/),
  more("twh", "limgiong", "林強", ["林強", "Lim Giong"], /^(林強|林强)($|\s*[,&])|lim giong/i),
  more("twh", "fireex", "滅火器", ["滅火器", "Fire EX."], /滅火器|灭火器|fire ex\.?/i),
  more("twh", "amazingshow", "美秀集團", ["美秀集團", "Amazing Show"], /美秀集團|美秀集团|amazing show/i),
  more("twh", "chthonic", "閃靈", ["閃靈", "Chthonic"], /閃靈|闪灵|chthonic/i),
  more("twh", "sorryyouth", "拍謝少年", ["拍謝少年", "Sorry Youth"], /拍謝少年|拍谢少年|sorry youth/i),
  more("twh", "chairman", "董事長樂團", ["董事長樂團", "The Chairman"], /董事長樂團|董事长乐团|the chairman/i, { short: "董事長" }),
);

// ---------- 2026 擴充：依各地最新排行補齊 ----------
// 參考 KKBOX 風雲榜、Billboard Artist 100、Billboard JAPAN 上半期、Melon 上半期、Spotify Wrapped 等榜單，
// 兼顧現在正紅與各年代經典。很短或很常見的名字一樣用 ^…$ 比對整個歌手名稱。
window.ARTISTS.push(
  // 台灣（含長年在台灣發片的星馬歌手）
  more("tw", "jjlin", "林俊傑", ["林俊傑", "JJ Lin"], /林俊傑|林俊杰|jj lin/i),
  more("tw", "stefanie", "孫燕姿", ["孫燕姿", "Stefanie Sun"], /孫燕姿|孙燕姿|stefanie sun/i),
  more("tw", "fishleong", "梁靜茹", ["梁靜茹", "Fish Leong"], /梁靜茹|梁静茹|fish leong/i),
  more("tw", "tanya", "蔡健雅", ["蔡健雅", "Tanya Chua"], /蔡健雅|tanya chua/i),
  more("tw", "leehom", "王力宏", ["王力宏", "Leehom Wang"], /王力宏|leehom wang/i),
  more("tw", "showlo", "羅志祥", ["羅志祥", "Show Lo"], /羅志祥|罗志祥|show lo/i),
  more("tw", "elva", "蕭亞軒", ["蕭亞軒", "Elva Hsiao"], /蕭亞軒|萧亚轩|elva hsiao/i),
  more("tw", "alin", "A-Lin", ["A-Lin", "黃麗玲"], /^a-?lin(\s*[,&]|$)|黃麗玲|黄丽玲/i),
  more("tw", "jeffchang", "張信哲", ["張信哲", "Jeff Chang"], /張信哲|张信哲|jeff chang/i),
  more("tw", "bii", "畢書盡", ["畢書盡", "Bii"], /畢書盡|毕书尽|^bii(\s*[,&]|$)/i),
  more("tw", "christinefan", "范瑋琪", ["范瑋琪", "Christine Fan"], /范瑋琪|范玮琪|christine fan/i),
  more("tw", "rachelliang", "梁文音", ["梁文音", "Rachel Liang"], /梁文音|rachel liang/i),
  more("tw", "clairekuo", "郭靜", ["郭靜", "Claire Kuo"], /郭靜|郭静|claire kuo/i),
  more("tw", "terrylin", "林志炫", ["林志炫", "Terry Lin"], /林志炫|terry lin/i),
  more("tw", "philchang", "張宇", ["張宇"], /^(張宇|张宇)($|\s*[,&])/),
  more("tw", "michaelwong", "光良", ["光良", "Michael Wong"], /^光良($|\s*[,&])|^michael wong(\s*[,&]|$)/i),
  more("tw", "victorwong", "品冠", ["品冠", "Victor Wong"], /^品冠($|\s*[,&])|^victor wong(\s*[,&]|$)/i),
  more("tw", "samlee", "李聖傑", ["李聖傑"], /李聖傑|李圣杰/),
  more("tw", "garychaw", "曹格", ["曹格", "Gary Chaw"], /曹格|gary chaw/i),
  more("tw", "tigerhuang", "黃小琥", ["黃小琥", "Tiger Huang"], /黃小琥|黄小琥|tiger huang/i),
  more("tw", "pennytai", "戴佩妮", ["戴佩妮", "Penny Tai"], /戴佩妮|penny tai/i),
  more("tw", "mavisfan", "范曉萱", ["范曉萱", "Mavis Fan"], /范曉萱|范晓萱|mavis fan/i),
  more("tw", "tarcysu", "蘇慧倫", ["蘇慧倫", "Tarcy Su"], /蘇慧倫|苏慧伦|tarcy su/i),
  more("tw", "nickylee", "李玖哲", ["李玖哲", "Nicky Lee"], /李玖哲|nicky lee/i),
  more("tw", "aska", "楊宗緯", ["楊宗緯", "Aska Yang"], /楊宗緯|杨宗纬|aska yang/i),
  more("tw", "jesslee", "李佳薇", ["李佳薇", "Jess Lee"], /李佳薇|jess lee/i),
  more("tw", "alienhuang", "黃鴻升", ["黃鴻升", "Alien Huang"], /黃鴻升|黄鸿升|alien huang/i),
  more("tw", "della", "丁噹", ["丁噹", "Della"], /^(丁噹|丁当)($|\s*[,&])|^della(\s*[,&]|$)/i),
  more("tw", "aaronyan", "炎亞綸", ["炎亞綸", "Aaron Yan"], /炎亞綸|炎亚纶|aaron yan/i),
  more("tw", "xiaobingchih", "蕭秉治", ["蕭秉治", "Xiao Bing Chih"], /蕭秉治|萧秉治|xiao bing chih/i),
  more("tw", "ninechen", "陳零九", ["陳零九", "Nine Chen"], /陳零九|陈零九|^nine chen/i),
  more("tw", "fengze", "邱鋒澤", ["邱鋒澤", "Feng Ze"], /邱鋒澤|邱锋泽/),
  more("tw", "zhengxing", "鄭興", ["鄭興"], /^(鄭興|郑兴)($|\s*[,&])/),
  more("tw", "leeyuting", "李友廷", ["李友廷"], /李友廷/),
  more("tw", "chihsiou", "持修", ["持修"], /^持修($|\s*[,&])/),
  more("tw", "juliawu", "吳卓源", ["吳卓源", "Julia Wu"], /吳卓源|吴卓源|julia wu/i),
  more("tw", "kimberley", "陳芳語", ["陳芳語", "Kimberley Chen"], /陳芳語|陈芳语|kimberley chen/i),
  more("tw", "rchord", "謝和弦", ["謝和弦", "R-chord"], /謝和弦|谢和弦|r-chord/i),
  more("tw", "nickthereal", "周湯豪", ["周湯豪", "NICKTHEREAL"], /周湯豪|周汤豪|nickthereal/i),
  more("tw", "mchotdog", "熱狗", ["熱狗", "MC HotDog"], /^mc ?hot ?dog|^(熱狗|热狗)($|\s*[,&])/i),
  more("tw", "softlipa", "蛋堡", ["蛋堡", "Soft Lipa"], /蛋堡|soft lipa/i),
  more("tw", "eso", "瘦子 E.SO", ["瘦子", "E.SO"], /^瘦子|^e\.?so(\s*[,&]|$)/i, { short: "瘦子" }),
  more("tw", "shou", "婁峻碩", ["婁峻碩", "SHOU"], /婁峻碩|娄峻硕/),
  more("tw", "osn", "高爾宣", ["高爾宣", "OSN"], /高爾宣|高尔宣|^osn(\s*[,&]|$)/i),
  more("tw", "gugu", "鼓鼓", ["鼓鼓", "呂思緯"], /鼓鼓|呂思緯|吕思纬/),
  more("tw", "mixer", "麋先生", ["麋先生", "Mixer"], /麋先生|^mixer$/i),
  more("tw", "shazi", "傻子與白痴", ["傻子與白痴"], /傻子與白痴|傻子与白痴/),
  more("tw", "papun", "怕胖團", ["怕胖團", "PAPUN BAND"], /怕胖團|怕胖团|papun band/i),
  more("tw", "bestards", "理想混蛋", ["理想混蛋", "Bestards"], /理想混蛋|bestards/i),
  more("tw", "sweetjohn", "甜約翰", ["甜約翰", "Sweet John"], /甜約翰|甜约翰|sweet john/i),
  more("tw", "lotayu", "羅大佑", ["羅大佑", "Lo Ta-yu"], /羅大佑|罗大佑|lo ta-?yu/i),
  more("tw", "tsaichin", "蔡琴", ["蔡琴", "Tsai Chin"], /^蔡琴($|\s*[,&])|^tsai chin(\s*[,&]|$)/i),
  more("tw", "winniehsin", "辛曉琪", ["辛曉琪", "Winnie Hsin"], /辛曉琪|辛晓琪|winnie hsin/i),
  more("tw", "wanfang", "萬芳", ["萬芳"], /^(萬芳|万芳)($|\s*[,&])/),

  // 台語
  more("twh", "911", "玖壹壹", ["玖壹壹"], /玖壹壹|^nine one one/i),
  more("twh", "caotun", "草屯囝仔", ["草屯囝仔"], /草屯囝仔/),
  more("twh", "linjunyi", "林俊逸", ["林俊逸"], /林俊逸/),
  more("twh", "caoyawen", "曹雅雯", ["曹雅雯"], /曹雅雯/),
  more("twh", "caijialin", "蔡佳麟", ["蔡佳麟"], /蔡佳麟/),
  more("twh", "xianghuiling", "向蕙玲", ["向蕙玲"], /向蕙玲/),
  more("twh", "yutian", "余天", ["余天"], /^余天($|\s*[,&])/),
  more("twh", "chenxiaoyun", "陳小雲", ["陳小雲"], /陳小雲|陈小云/),
  more("twh", "huangxitian", "黃西田", ["黃西田"], /黃西田|黄西田/),
  more("twh", "guojinfa", "郭金發", ["郭金發"], /郭金發|郭金发/),
  more("twh", "jiangshuna", "江淑娜", ["江淑娜"], /江淑娜/),
  more("twh", "wangruixia", "王瑞霞", ["王瑞霞"], /王瑞霞/),
  more("twh", "xiulanmaya", "秀蘭瑪雅", ["秀蘭瑪雅"], /秀蘭瑪雅|秀兰玛雅/),
  more("twh", "leechienna", "李千娜", ["李千娜"], /李千娜/),
  more("twh", "hsufukai", "許富凱", ["許富凱"], /許富凱|许富凯/),
  more("twh", "chensuiyi", "陳隨意", ["陳隨意"], /陳隨意|陈随意/),
  more("twh", "enno", "鄭宜農", ["鄭宜農", "Enno Cheng"], /鄭宜農|郑宜农|enno cheng/i),

  // 中國
  more("cn", "silence", "汪蘇瀧", ["汪蘇瀧", "汪苏泷", "Silence Wang"], /汪蘇瀧|汪苏泷|silence wang/i),
  more("cn", "xusong", "許嵩", ["許嵩", "许嵩", "Vae"], /許嵩|许嵩/),
  more("cn", "jasonzhang", "張杰", ["張杰", "张杰", "Jason Zhang"], /^(張杰|张杰)($|\s*[,&])|^jason zhang(\s*[,&]|$)/i),
  more("cn", "roywang", "王源", ["王源", "Roy Wang"], /^王源($|\s*[,&])|^roy wang(\s*[,&]|$)/i, { related: ["tfboys"] }),
  more("cn", "jacksonyee", "易烊千璽", ["易烊千璽", "易烊千玺", "Jackson Yee"], /易烊千璽|易烊千玺|jackson yee/i, { related: ["tfboys"] }),
  more("cn", "karrywang", "王俊凱", ["王俊凱", "王俊凯", "Karry Wang"], /王俊凱|王俊凯|karry wang/i, { related: ["tfboys"] }),
  more("cn", "tfboys", "TFBOYS", ["TFBOYS"], /^tfboys(\s*[,&]|$)/i),
  more("cn", "tnt", "時代少年團", ["時代少年團", "时代少年团"], /時代少年團|时代少年团|teens in times/i),
  more("cn", "kun", "蔡徐坤", ["蔡徐坤", "KUN"], /蔡徐坤|cai xukun/i),
  more("cn", "lay", "張藝興", ["張藝興", "张艺兴", "Lay Zhang"], /張藝興|张艺兴|lay zhang/i),
  more("cn", "luhan", "鹿晗", ["鹿晗", "Luhan"], /^鹿晗($|\s*[,&])|^lu ?han(\s*[,&]|$)/i),
  more("cn", "zhangbichen", "張碧晨", ["張碧晨", "张碧晨"], /張碧晨|张碧晨|diamond zhang/i),
  more("cn", "shanyichun", "單依純", ["單依純", "单依纯"], /單依純|单依纯|shan yichun/i),
  more("cn", "liyuchun", "李宇春", ["李宇春", "Chris Lee"], /李宇春/),
  more("cn", "liuyuning", "劉宇寧", ["劉宇寧", "刘宇宁"], /劉宇寧|刘宇宁/),
  more("cn", "zhengrunze", "鄭潤澤", ["鄭潤澤", "郑润泽"], /鄭潤澤|郑润泽/),
  more("cn", "huxia", "胡夏", ["胡夏"], /^胡夏($|\s*[,&])/),
  more("cn", "zhangyuan", "張遠", ["張遠", "张远"], /^(張遠|张远)($|\s*[,&])/),
  more("cn", "laofan", "隔壁老樊", ["隔壁老樊"], /隔壁老樊/),
  more("cn", "huangzihongfan", "黃子弘凡", ["黃子弘凡", "黄子弘凡"], /黃子弘凡|黄子弘凡/),
  more("cn", "jinzhiwen", "金志文", ["金志文"], /金志文/),
  more("cn", "wangjingwen", "王靖雯", ["王靖雯"], /王靖雯/),
  more("cn", "yisayu", "郁可唯", ["郁可唯", "Yisa Yu"], /郁可唯|yisa yu/i),
  more("cn", "huangxiaoyun", "黃霄雲", ["黃霄雲", "黄霄云"], /黃霄雲|黄霄云/),
  more("cn", "bibizhou", "周筆暢", ["周筆暢", "周笔畅", "Bibi Zhou"], /周筆暢|周笔畅|bibi zhou/i),
  more("cn", "tanweiwei", "譚維維", ["譚維維", "谭维维", "Tan Weiwei"], /譚維維|谭维维|tan weiwei/i),
  more("cn", "hanhong", "韓紅", ["韓紅", "韩红"], /^(韓紅|韩红)($|\s*[,&])/),
  more("cn", "daolang", "刀郎", ["刀郎", "Dao Lang"], /^刀郎($|\s*[,&])|^dao lang(\s*[,&]|$)/i),
  more("cn", "phoenix", "鳳凰傳奇", ["鳳凰傳奇", "凤凰传奇"], /鳳凰傳奇|凤凰传奇|phoenix legend/i),
  more("cn", "cuijian", "崔健", ["崔健", "Cui Jian"], /^崔健($|\s*[,&])|^cui jian(\s*[,&]|$)/i),
  more("cn", "wangfeng", "汪峰", ["汪峰"], /^汪峰($|\s*[,&])/),
  more("cn", "xuwei", "許巍", ["許巍", "许巍"], /許巍|许巍/),
  more("cn", "songdongye", "宋冬野", ["宋冬野"], /宋冬野/),
  more("cn", "zhaolei", "趙雷", ["趙雷", "赵雷"], /趙雷|赵雷/),
  more("cn", "chenli", "陳粒", ["陳粒", "陈粒"], /^(陳粒|陈粒)($|\s*[,&])/),
  more("cn", "fangdong", "房東的貓", ["房東的貓", "房东的猫"], /房東的貓|房东的猫/),
  more("cn", "gai", "GAI 周延", ["GAI", "周延"], /^gai(\s*[,&]|$)|^周延($|\s*[,&])/i, { short: "GAI" }),
  more("cn", "higherbrothers", "Higher Brothers", ["Higher Brothers", "更高兄弟"], /higher brothers/i),
  more("cn", "omnipotent", "萬能青年旅店", ["萬能青年旅店", "万能青年旅店"], /萬能青年旅店|万能青年旅店|omnipotent youth/i, { short: "萬青" }),
  more("cn", "newpants", "新褲子", ["新褲子", "新裤子", "New Pants"], /新褲子|新裤子|new pants/i),

  // 日本
  // HANA 區分大小寫，避免抓到名字叫 Hana 的其他歌手
  more("jp", "hana", "HANA", ["HANA"], /^HANA(\s*[,&]|$)/),
  more("jp", "milk", "M!LK", ["M!LK"], /^m!lk(\s*[,&]|$)/i),
  more("jp", "chanmina", "ちゃんみな", ["ちゃんみな", "Chanmina"], /ちゃんみな|chanmina/i),
  more("jp", "snowman", "Snow Man", ["Snow Man"], /^snow man(\s*[,&]|$)/i),
  more("jp", "creepynuts", "Creepy Nuts", ["Creepy Nuts"], /creepy nuts/i),
  more("jp", "tuki", "tuki.", ["tuki."], /^tuki\.?(\s*[,&]|$)/i),
  more("jp", "yuuri", "優里", ["優里", "Yuuri"], /^優里($|\s*[,&])|^yuuri(\s*[,&]|$)/i),
  more("jp", "fujiikaze", "藤井風", ["藤井風", "Fujii Kaze"], /藤井\s?風|fujii kaze/i),
  more("jp", "sekainoowari", "SEKAI NO OWARI", ["SEKAI NO OWARI"], /sekai no owari/i),
  more("jp", "radwimps", "RADWIMPS", ["RADWIMPS"], /radwimps/i),
  more("jp", "spitz", "スピッツ", ["スピッツ", "Spitz"], /スピッツ|^spitz$/i),
  more("jp", "milet", "milet", ["milet"], /^milet(\s*[,&×x]|$)/i),
  more("jp", "zutomayo", "ずっと真夜中でいいのに。", ["ずっと真夜中でいいのに。", "ZUTOMAYO"], /ずっと真夜中でいいのに|zutomayo/i, { short: "ずとまよ" }),
  more("jp", "yorushika", "ヨルシカ", ["ヨルシカ", "Yorushika"], /ヨルシカ|yorushika/i),
  more("jp", "aimer", "Aimer", ["Aimer"], /^aimer(\s*[,&×x]|$)/i),
  more("jp", "bz", "B'z", ["B'z"], /^b['’]z(\s*[,&]|$)/i),
  more("jp", "arashi", "嵐", ["嵐", "ARASHI"], /^(嵐|arashi)(\s*[,&]|$)/i),
  more("jp", "mrchildren", "Mr.Children", ["Mr.Children"], /mr\.? ?children/i),
  more("jp", "southern", "サザンオールスターズ", ["サザンオールスターズ", "Southern All Stars"], /サザンオールスターズ|southern all stars/i, { short: "サザン" }),
  more("jp", "dreamscometrue", "DREAMS COME TRUE", ["DREAMS COME TRUE"], /dreams come true/i, { short: "ドリカム" }),
  more("jp", "sheenaringo", "椎名林檎", ["椎名林檎", "Sheena Ringo"], /椎名林檎|sheena ringo|ringo sheena/i),
  more("jp", "namie", "安室奈美恵", ["安室奈美恵", "Namie Amuro"], /安室奈美恵|namie amuro/i),
  more("jp", "ayu", "浜崎あゆみ", ["浜崎あゆみ", "Ayumi Hamasaki"], /浜崎あゆみ|ayumi hamasaki/i),
  more("jp", "perfume", "Perfume", ["Perfume"], /^perfume(\s*[,&]|$)/i),
  more("jp", "babymetal", "BABYMETAL", ["BABYMETAL"], /babymetal/i),
  more("jp", "oneokrock", "ONE OK ROCK", ["ONE OK ROCK"], /one ok rock/i),
  more("jp", "bump", "BUMP OF CHICKEN", ["BUMP OF CHICKEN"], /bump of chicken/i),
  more("jp", "ikimono", "いきものがかり", ["いきものがかり", "Ikimonogakari"], /いきものがかり|ikimonogakari/i),
  more("jp", "nogizaka", "乃木坂46", ["乃木坂46", "Nogizaka46"], /乃木坂46|nogizaka46/i),
  more("jp", "numberi", "Number_i", ["Number_i"], /^number_i(\s*[,&]|$)/i),
  more("jp", "atarashii", "新しい学校のリーダーズ", ["新しい学校のリーダーズ", "ATARASHII GAKKO!"], /新しい学校のリーダーズ|atarashii gakko/i, { short: "新しい学校" }),
  more("jp", "hoshinogen", "星野源", ["星野源", "Gen Hoshino"], /星野源|gen hoshino/i),
  more("jp", "saucydog", "Saucy Dog", ["Saucy Dog"], /saucy dog/i),
  more("jp", "imase", "imase", ["imase"], /^imase(\s*[,&]|$)/i),
  more("jp", "ryokuoushoku", "緑黄色社会", ["緑黄色社会", "Ryokuoushoku Shakai"], /緑黄色社会|ryokuoushoku shakai/i, { short: "リョクシャカ" }),
  more("jp", "befirst", "BE:FIRST", ["BE:FIRST"], /^be:first(\s*[,&]|$)/i),
  more("jp", "sakanaction", "サカナクション", ["サカナクション", "sakanaction"], /サカナクション|sakanaction/i),
  more("jp", "tatsuro", "山下達郎", ["山下達郎", "Tatsuro Yamashita"], /山下達郎|tatsuro yamashita/i),
  more("jp", "mariya", "竹内まりや", ["竹内まりや", "Mariya Takeuchi"], /竹内まりや|mariya takeuchi/i),

  // 韓國
  // IVE、TWS 區分大小寫，避免抓到英文歌名裡的同名歌手
  more("kr", "ive", "IVE", ["IVE"], /^IVE(\s*[,&]|$)/),
  more("kr", "akmu", "AKMU", ["AKMU"], /^akmu|akdong musician/i),
  more("kr", "cortis", "CORTIS", ["CORTIS"], /^cortis(\s*[,&]|$)/i),
  more("kr", "ioi", "I.O.I", ["I.O.I"], /^i\.o\.i(\s*[,&]|$)/i),
  more("kr", "rescene", "RESCENE", ["RESCENE"], /^rescene(\s*[,&]|$)/i),
  more("kr", "aespa", "aespa", ["aespa"], /^aespa(\s*[,&]|$)/i),
  more("kr", "lesserafim", "LE SSERAFIM", ["LE SSERAFIM"], /le sserafim/i),
  more("kr", "seventeen", "SEVENTEEN", ["SEVENTEEN"], /^seventeen(\s*[,&]|$)/i),
  more("kr", "idle", "i-dle", ["i-dle", "(G)I-DLE"], /^(\(g\))?i-dle(\s*[,&]|$)/i),
  more("kr", "illit", "ILLIT", ["ILLIT"], /^illit(\s*[,&]|$)/i),
  more("kr", "babymonster", "BABYMONSTER", ["BABYMONSTER"], /^babymonster(\s*[,&]|$)/i),
  more("kr", "day6", "DAY6", ["DAY6"], /^day6(\s*[,&]|$)/i),
  more("kr", "bigbang", "BIGBANG", ["BIGBANG"], /^big ?bang(\s*[,&]|$)/i),
  more("kr", "gdragon", "G-DRAGON", ["G-DRAGON"], /g-dragon/i, { short: "GD", related: ["bigbang"] }),
  more("kr", "rose", "ROSÉ", ["ROSÉ", "Rose"], /^ros[eé](\s*[,&]|$)/i, { related: ["blackpink"] }),
  more("kr", "jennie", "JENNIE", ["JENNIE"], /^jennie(\s*[,&]|$)/i, { related: ["blackpink"] }),
  more("kr", "jisoo", "JISOO", ["JISOO"], /^jisoo(\s*[,&]|$)/i, { related: ["blackpink"] }),
  more("kr", "jimin", "Jimin", ["Jimin"], /^jimin(\s*[,&]|$)/i, { related: ["bts"] }),
  more("kr", "jungkook", "Jung Kook", ["Jung Kook"], /^jung ?kook(\s*[,&]|$)/i, { related: ["bts"] }),
  more("kr", "txt", "TOMORROW X TOGETHER", ["TOMORROW X TOGETHER", "TXT"], /tomorrow x together/i, { short: "TXT" }),
  more("kr", "enhypen", "ENHYPEN", ["ENHYPEN"], /^enhypen(\s*[,&]|$)/i),
  more("kr", "nctdream", "NCT DREAM", ["NCT DREAM"], /^nct dream(\s*[,&]|$)/i),
  more("kr", "exo", "EXO", ["EXO"], /^exo(\s*[,&]|$)/i),
  more("kr", "redvelvet", "Red Velvet", ["Red Velvet"], /^red velvet(\s*[,&]|$)/i),
  more("kr", "snsd", "少女時代", ["少女時代", "Girls' Generation"], /girls['’] generation|少女時代|少女时代/i),
  more("kr", "mamamoo", "MAMAMOO", ["MAMAMOO"], /^mamamoo(\s*[,&]|$)/i),
  more("kr", "itzy", "ITZY", ["ITZY"], /^itzy(\s*[,&]|$)/i),
  more("kr", "kissoflife", "KISS OF LIFE", ["KISS OF LIFE"], /kiss of life/i),
  more("kr", "riize", "RIIZE", ["RIIZE"], /^riize(\s*[,&]|$)/i),
  more("kr", "boynextdoor", "BOYNEXTDOOR", ["BOYNEXTDOOR"], /boynextdoor/i),
  more("kr", "zb1", "ZEROBASEONE", ["ZEROBASEONE"], /zerobaseone/i),
  more("kr", "ateez", "ATEEZ", ["ATEEZ"], /^ateez(\s*[,&]|$)/i),
  more("kr", "taeyeon", "TAEYEON", ["TAEYEON"], /^taeyeon(\s*[,&]|$)/i, { related: ["snsd"] }),
  more("kr", "qwer", "QWER", ["QWER"], /^qwer(\s*[,&]|$)/i),
  more("kr", "plave", "PLAVE", ["PLAVE"], /^plave(\s*[,&]|$)/i),
  more("kr", "hearts2hearts", "Hearts2Hearts", ["Hearts2Hearts"], /hearts2hearts/i),
  more("kr", "meovv", "MEOVV", ["MEOVV"], /^meovv(\s*[,&]|$)/i),
  more("kr", "tws", "TWS", ["TWS"], /^TWS(\s*[,&]|$)/),
  more("kr", "nmixx", "NMIXX", ["NMIXX"], /^nmixx(\s*[,&]|$)/i),
  more("kr", "shinee", "SHINee", ["SHINee"], /^shinee(\s*[,&]|$)/i),
  more("kr", "superjunior", "SUPER JUNIOR", ["SUPER JUNIOR"], /^super junior(\s*[,&]|$)/i),
  more("kr", "2ne1", "2NE1", ["2NE1"], /^2ne1(\s*[,&]|$)/i),
  more("kr", "limyoungwoong", "林英雄", ["임영웅", "Lim Young Woong"], /임영웅|lim young ?woong/i),

  // 歐美
  more("west", "noahkahan", "Noah Kahan", ["Noah Kahan"], /noah kahan/i),
  more("west", "ellalangley", "Ella Langley", ["Ella Langley"], /ella langley/i),
  more("west", "chappell", "Chappell Roan", ["Chappell Roan"], /chappell roan/i, { short: "Chappell" }),
  more("west", "gracie", "Gracie Abrams", ["Gracie Abrams"], /gracie abrams/i, { short: "Gracie" }),
  more("west", "tatemcrae", "Tate McRae", ["Tate McRae"], /tate mcrae/i),
  more("west", "zachbryan", "Zach Bryan", ["Zach Bryan"], /zach bryan/i),
  more("west", "lukecombs", "Luke Combs", ["Luke Combs"], /luke combs/i),
  more("west", "shaboozey", "Shaboozey", ["Shaboozey"], /shaboozey/i),
  more("west", "bensonboone", "Benson Boone", ["Benson Boone"], /benson boone/i),
  more("west", "teddyswims", "Teddy Swims", ["Teddy Swims"], /teddy swims/i),
  more("west", "alexwarren", "Alex Warren", ["Alex Warren"], /alex warren/i),
  more("west", "hozier", "Hozier", ["Hozier"], /^hozier(\s*[,&]|$)/i),
  more("west", "oliviadean", "Olivia Dean", ["Olivia Dean"], /olivia dean/i),
  more("west", "sombr", "sombr", ["sombr"], /^sombr(\s*[,&]|$)/i),
  more("west", "laufey", "Laufey", ["Laufey"], /^laufey(\s*[,&]|$)/i),
  more("west", "conangray", "Conan Gray", ["Conan Gray"], /conan gray/i),
  more("west", "katseye", "KATSEYE", ["KATSEYE"], /^katseye(\s*[,&]|$)/i),
  more("west", "tyler", "Tyler, The Creator", ["Tyler, The Creator"], /tyler,? the creator/i, { short: "Tyler" }),
  more("west", "carti", "Playboi Carti", ["Playboi Carti"], /playboi carti/i),
  more("west", "21savage", "21 Savage", ["21 Savage"], /^21 savage/i),
  more("west", "lilbaby", "Lil Baby", ["Lil Baby"], /^lil baby(\s*[,&]|$)/i),
  more("west", "lilnasx", "Lil Nas X", ["Lil Nas X"], /lil nas x/i),
  more("west", "lizzo", "Lizzo", ["Lizzo"], /^lizzo(\s*[,&]|$)/i),
  more("west", "megan", "Megan Thee Stallion", ["Megan Thee Stallion"], /megan thee stallion/i, { short: "Megan" }),
  more("west", "doechii", "Doechii", ["Doechii"], /^doechii(\s*[,&]|$)/i),
  more("west", "jcole", "J. Cole", ["J. Cole"], /^j\.? cole(\s*[,&]|$)/i),
  more("west", "jackharlow", "Jack Harlow", ["Jack Harlow"], /jack harlow/i),
  more("west", "metroboomin", "Metro Boomin", ["Metro Boomin"], /metro boomin/i),
  more("west", "juicewrld", "Juice WRLD", ["Juice WRLD"], /juice wrld/i),
  more("west", "kidlaroi", "The Kid LAROI", ["The Kid LAROI"], /kid laroi/i),
  more("west", "pitbull", "Pitbull", ["Pitbull"], /^pitbull(\s*[,&]|$)/i),
  more("west", "khalid", "Khalid", ["Khalid"], /^khalid(\s*[,&]|$)/i),
  more("west", "halsey", "Halsey", ["Halsey"], /^halsey(\s*[,&]|$)/i),
  more("west", "lorde", "Lorde", ["Lorde"], /^lorde(\s*[,&]|$)/i),
  more("west", "charlixcx", "Charli xcx", ["Charli xcx"], /charli ?xcx/i),
  more("west", "jamesarthur", "James Arthur", ["James Arthur"], /james arthur/i),
  more("west", "stapleton", "Chris Stapleton", ["Chris Stapleton"], /chris stapleton/i),
  more("west", "kygo", "Kygo", ["Kygo"], /^kygo(\s*[,&]|$)/i),
  more("west", "killers", "The Killers", ["The Killers"], /^the killers$/i),
  more("west", "foofighters", "Foo Fighters", ["Foo Fighters"], /foo fighters/i),
  more("west", "paramore", "Paramore", ["Paramore"], /^paramore(\s*[,&]|$)/i),
  more("west", "fob", "Fall Out Boy", ["Fall Out Boy"], /fall out boy/i),
  more("west", "panic", "Panic! At The Disco", ["Panic! At The Disco"], /panic! at the disco/i, { short: "Panic!" }),
  more("west", "gorillaz", "Gorillaz", ["Gorillaz"], /^gorillaz(\s*[,&]|$)/i),
  more("west", "the1975", "The 1975", ["The 1975"], /^the 1975$/i),
  more("west", "jonasbrothers", "Jonas Brothers", ["Jonas Brothers"], /jonas brothers/i),
  more("west", "onedirection", "One Direction", ["One Direction"], /^one direction$/i, { short: "1D" }),
  more("west", "bsb", "Backstreet Boys", ["Backstreet Boys"], /backstreet boys/i),
  more("west", "nsync", "*NSYNC", ["NSYNC"], /^\*?nsync(\s*[,&]|$)/i),
  more("west", "spicegirls", "Spice Girls", ["Spice Girls"], /spice girls/i),
  more("west", "destinyschild", "Destiny's Child", ["Destiny's Child"], /destiny['’]?s child/i),
  more("west", "avril", "Avril Lavigne", ["Avril Lavigne"], /avril lavigne/i, { short: "Avril" }),
  more("west", "aguilera", "Christina Aguilera", ["Christina Aguilera"], /christina aguilera/i, { short: "Xtina" }),
  more("west", "janet", "Janet Jackson", ["Janet Jackson"], /janet jackson/i, { short: "Janet" }),
  more("west", "tinaturner", "Tina Turner", ["Tina Turner"], /tina turner/i),
  more("west", "amywinehouse", "Amy Winehouse", ["Amy Winehouse"], /amy winehouse/i, { short: "Amy" }),
  more("west", "dolly", "Dolly Parton", ["Dolly Parton"], /dolly parton/i, { short: "Dolly" }),
  more("west", "bryanadams", "Bryan Adams", ["Bryan Adams"], /bryan adams/i),
  more("west", "philcollins", "Phil Collins", ["Phil Collins"], /phil collins/i),
  more("west", "georgemichael", "George Michael", ["George Michael"], /george michael/i),
  more("west", "billyjoel", "Billy Joel", ["Billy Joel"], /billy joel/i),
  more("west", "springsteen", "Bruce Springsteen", ["Bruce Springsteen"], /bruce springsteen/i, { short: "Springsteen" }),
  more("west", "johnnycash", "Johnny Cash", ["Johnny Cash"], /johnny cash/i),
  more("west", "sinatra", "Frank Sinatra", ["Frank Sinatra"], /frank sinatra/i, { short: "Sinatra" }),

  // 拉丁
  more("latin", "pesopluma", "Peso Pluma", ["Peso Pluma"], /peso pluma/i),
  more("latin", "feid", "Feid", ["Feid"], /^feid(\s*[,&]|$)/i),
  more("latin", "rauw", "Rauw Alejandro", ["Rauw Alejandro"], /rauw alejandro/i, { short: "Rauw" }),

  // 印度
  more("in", "pritam", "Pritam", ["Pritam"], /^pritam(\s*[,&]|$)/i),
  more("in", "anirudh", "Anirudh Ravichander", ["Anirudh Ravichander"], /anirudh ravichander/i, { short: "Anirudh" }),
  more("in", "sachinjigar", "Sachin-Jigar", ["Sachin-Jigar"], /sachin[- ]jigar/i),
  more("in", "diljit", "Diljit Dosanjh", ["Diljit Dosanjh"], /diljit dosanjh/i, { short: "Diljit" }),
  more("in", "adityarikhari", "Aditya Rikhari", ["Aditya Rikhari"], /aditya rikhari/i),
  more("in", "anuvjain", "Anuv Jain", ["Anuv Jain"], /anuv jain/i),
  more("in", "jasleen", "Jasleen Royal", ["Jasleen Royal"], /jasleen royal/i),

  // 泰國
  // 區分大小寫，避免和日本的 LiSA 混在一起
  more("th", "lisa", "LISA", ["LISA", "Lalisa"], /^LISA(\s*[,&]|$)/, { related: ["blackpink"] }),
  more("th", "jeffsatur", "Jeff Satur", ["Jeff Satur"], /jeff satur/i),
  more("th", "tillybirds", "Tilly Birds", ["Tilly Birds"], /tilly birds/i),
  more("th", "fhero", "F.HERO", ["F.HERO"], /^f\.?hero(\s*[,&]|$)/i),
  more("th", "saran", "SARAN", ["SARAN"], /^saran(\s*[,&]|$)/i),
  more("th", "4eve", "4EVE", ["4EVE"], /^4eve(\s*[,&]|$)/i),
  more("th", "threemandown", "Three Man Down", ["Three Man Down"], /three man down/i),
);

// 全球百大：串流與歷史銷量都有考量，兼顧經典與現役，依名次排列
window.TOP100 = [
  "taylor", "drake", "badbunny", "weeknd", "edsheeran", "ariana", "bieber", "eminem", "bts", "billie",
  "rihanna", "postmalone", "coldplay", "bruno", "dualipa", "gaga", "beyonce", "adele", "mj", "kendrick",
  "sza", "dojacat", "harrystyles", "olivia", "imaginedragons", "maroon5", "katyperry", "shakira", "jbalvin", "karolg",
  "sabrina", "lanadelrey", "arcticmonkeys", "linkinpark", "queen", "beatles", "eltonjohn", "madonna", "whitney", "mariah",
  "elvis", "abba", "bobmarley", "nirvana", "metallica", "acdc", "gnr", "rhcp", "oasis", "radiohead",
  "u2", "bonjovi", "pinkfloyd", "ledzeppelin", "rollingstones", "fleetwoodmac", "eagles", "prince", "steviewonder", "bowie",
  "britney", "timberlake", "usher", "aliciakeys", "sia", "shawnmendes", "charlieputh", "samsmith", "capaldi", "onerepublic",
  "calvinharris", "guetta", "avicii", "daftpunk", "marshmello", "chainsmokers", "travisscott", "future", "nickiminaj", "cardib",
  "jayz", "snoop", "fiftycent", "daddyyankee", "ozuna", "rosalia", "selena", "miley", "pink", "greenday",
  "twentyonepilots", "blackpink", "twice", "newjeans", "straykids", "psy", "frankocean", "celine", "morganwallen", "iu",
];

// 搜尋用的中文俗稱
const ALIASES = {
  gaga: "女神卡卡 卡卡", mj: "麥可傑克森 麥可 流行天王", bruno: "火星人布魯諾 火星人", ariana: "亞莉安娜 A妹",
  taylor: "泰勒絲 霉霉", edsheeran: "紅髮艾德", billie: "怪奇比莉", weeknd: "威肯 盛宴", adele: "愛黛兒",
  dualipa: "杜娃黎波", coldplay: "酷玩樂團", beyonce: "碧昂絲", bieber: "小賈斯汀", olivia: "奧莉維亞",
  drake: "德瑞克 公鴨", eminem: "阿姆", rihanna: "蕾哈娜", postmalone: "波茲瑪龍 小馬", kendrick: "肯卓克",
  dojacat: "朵佳貓", harrystyles: "哈利 哈利史泰爾斯", imaginedragons: "謎幻樂團", maroon5: "魔力紅",
  katyperry: "凱蒂佩芮 水果姐", sabrina: "莎賓娜", lanadelrey: "拉娜德芮", arcticmonkeys: "北極潑猴",
  linkinpark: "聯合公園", queen: "皇后合唱團", beatles: "披頭四", eltonjohn: "艾爾頓強", madonna: "瑪丹娜",
  whitney: "惠妮休斯頓", mariah: "瑪麗亞凱莉 牛姐", elvis: "貓王", abba: "阿巴合唱團", bobmarley: "巴布馬利",
  nirvana: "超脫樂團", metallica: "金屬製品", gnr: "槍與玫瑰", rhcp: "嗆辣紅椒", oasis: "綠洲合唱團",
  radiohead: "電台司令", bonjovi: "邦喬飛", pinkfloyd: "平克佛洛伊德", ledzeppelin: "齊柏林飛船",
  rollingstones: "滾石樂團", fleetwoodmac: "佛利伍麥克", eagles: "老鷹合唱團", prince: "王子",
  steviewonder: "史提夫汪達", bowie: "大衛鮑伊", britney: "小甜甜布蘭妮 布蘭妮", timberlake: "賈斯汀",
  aliciakeys: "艾莉西亞凱斯", shawnmendes: "尚恩曼德斯", charlieputh: "查理普斯", samsmith: "山姆史密斯",
  calvinharris: "凱文哈里斯", avicii: "艾維奇", daftpunk: "傻瓜龐克", marshmello: "棉花糖",
  chainsmokers: "老菸槍", nickiminaj: "妮琪米娜", selena: "席琳娜", miley: "麥莉", pink: "紅粉佳人",
  greenday: "年輕歲月", celine: "席琳狄翁", bts: "防彈少年團 防彈", blackpink: "粉墨",
  psy: "江南大叔", iu: "李知恩", badbunny: "壞痞兔", shakira: "夏奇拉",
  jay: "周董", amei: "阿妹", jolin: "Jolin", hebe: "Hebe", mayday: "阿信",
  cyndi: "甜心教主 心凌", sodagreen: "魚丁糸 青峰", teresateng: "小鄧", feiyuching: "小哥", jonathanlee: "老李",
  wakin: "華健", richiejen: "小齊", ayue: "阿嶽", harlemyu: "哈林", she: "Selina Hebe Ella", jody: "二姊",
  wubai: "伍佰老師 China Blue", jeannie: "姊姊", caodong: "草東", amazingshow: "美秀", deserts: "安溥",
  mangojump: "芒果醬 芒果 Mango Jump",
  onesong: "灣生樂團 灣聲 One Song 李哲藝 管弦樂",
};

// 名字結尾是英文或數字才補空格：「Gaga 猜歌王」、「周杰倫猜歌王」
window.withName = (name, rest) => (/[A-Za-z0-9.]$/.test(name) ? `${name} ${rest}` : `${name}${rest}`);

// 用地區預設值補齊每位歌手沒寫到的欄位
for (const artist of window.ARTISTS) {
  const region = window.REGIONS.find((r) => r.id === artist.region);
  const short = artist.short || artist.name;
  Object.assign(artist, {
    short,
    icon: artist.icon || region.icon,
    countries: artist.countries || region.countries,
    colors: artist.colors || region.colors,
    tagline: artist.tagline || window.withName(artist.name, "的歌，你認得幾首？"),
    top: window.TOP100.indexOf(artist.id) + 1 || null,
    // 搜尋用：名稱、搜尋關鍵字與中文俗稱全部串起來
    searchText: [artist.name, artist.short, ...(artist.terms || []), ALIASES[artist.id] || ""].join(" ").toLowerCase(),
    ranks: artist.ranks || [window.withName(short, "本人？👑"), "資深歌迷 🎧", "有在認真聽的路人 🙂", "先去多聽幾首再來 📀"],
  });
}

// 線索題庫的精簡寫法：
// t 歌名、a 專輯、y 專輯年份、f 冷知識、e emoji、w 自訂第二條線索（非專輯單曲或客串時用）、deep 非主打的冷門歌
window.CLUES = {};
window.defineClues = function (id, rows) {
  window.CLUES[id] = rows.map((r) => ({
    title: r.t,
    album: r.a || "",
    year: r.y,
    deep: Boolean(r.deep),
    clues: [r.f, r.w || `收錄於《${r.a}》（${r.y}）。`, r.e],
  }));
};
